version: "3.8"

services:
  api:
    build: .
    container_name: psico-health-api
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/falaDoutorDB
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: psico-health-db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
